Added SVG graphics support
abcum/pdflib pull request #2
Opened 2019-12-11 13:37 UTC by naueramant

2020-01-09 12:44 UTC, naueramant commented
ping

2020-07-02 11:16 UTC, naueramant commented
@abcum ?

2021-01-27 10:48 UTC, tobiemh requested changes
Hi @naueramant, apologies for missing this pull request!

Just a few minor changes, but otherwise I'll get this merged today.

2021-01-27 10:48 UTC, tobiemh commented on go.mod
> +module github.com/naueramant/pdflib
```suggestion
module github.com/abcum/pdflib
```

2021-01-27 10:48 UTC, tobiemh commented on include/golang.c
> +
Could these method definitions be in alphabetical order, among all the other method definitions?

2021-01-27 10:48 UTC, tobiemh commented on include/golang.h
> +
Could these method definitions be in alphabetical order, among all the other method definitions?

2021-01-27 10:48 UTC, tobiemh commented on include/pdflib.h
> +
Could these method definitions be in alphabetical order, among all the other method definitions?

2021-01-27 10:48 UTC, tobiemh commented on include/pdflib.h
> +                const char *optlist);
Could these method definitions be in alphabetical order, among all the other method definitions?

2021-01-27 10:48 UTC, tobiemh commented on main.go
> +
Could these method definitions be in alphabetical order, among all the other method definitions?

2021-01-27 15:03 UTC, naueramant commented
> Hi @naueramant, apologies for missing this pull request!
> 
> Just a few minor changes, but otherwise I'll get this merged today.

I will refactor the files asap 😄

2023-06-11 19:49 UTC, closed without merging